apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        args: ["--character-set-server=utf8"]
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: rootpassword
        - name: MYSQL_DATABASE
          value: "turkle"
        - name: MYSQL_USER
          value: "turkleuser"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: userpassword
              name: mysql

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pv-claim
